export const images = {
  logo: require("../../assets/img/logo.png"),
  qrLogo: require("../../assets/img/qr/qr-code.png"),
  fullLogo: require("../../assets/img/logo-blue-white.png"),
  profile: require("../../assets/img/profile.png"),
  blogger: require("../../assets/img/social-media/blogg.png"),
  twoCircle: require("../../assets/img/social-media/circleTwo.png"),
  fb: require("../../assets/img/social-media/fb.png"),
  googleBus: require("../../assets/img/social-media/googleBus.png"),
  insta: require("../../assets/img/social-media/insta.png"),
  internet: require("../../assets/img/social-media/int.png"),
  linkedin: require("../../assets/img/social-media/linkedin.png"),
  paypal: require("../../assets/img/social-media/pay.png"),
  pintrest: require("../../assets/img/social-media/pint.png"),
  plus: require("../../assets/img/social-media/plus.png"),
  skype: require("../../assets/img/social-media/skype.png"),
  ticktok: require("../../assets/img/social-media/tick.png"),
  twitter: require("../../assets/img/social-media/twit.png"),
  vim: require("../../assets/img/social-media/vim.png"),
  whatsapp: require("../../assets/img/social-media/whats.png"),
  youtube: require("../../assets/img/social-media/yt.png"),
  qr: require("../../assets/img/qr/qr.png"),
};
